/*
 * segment.h
 *
 *  Created on: Oct 15, 2014
 *      Author: nbingham
 */

#include <std/string.h>
#include "segment.h"
#include "tokenizer.h"

#pragma once

struct token_type
{
	token_type();
	virtual ~token_type();

	char name[32];

	token *parse(tokenizer &tokens) = 0;
};

/*
Token is an abstract base class for all token types. A given token type implements its own parsing function as generated by the grammar file. 
 */
struct token
{
	token();
	~token();

	token_type *type;
	slice<range<segment::iterator> > syntax;
	array<token*> tokens;
};
